### ISSUE TITLE
One Dispatcher (to rule them all), Permissions, Voters

### ISSUE THREAD

**Issue by olvlvl** [ICanBoogie/MessageBus#3]
One of the reasons to have distinct dispatchers for queries and commands was to be able to decorate the command dispatcher to restrict commands according to permissions, with the `AssertingDispatcher` for example. Now, we have a situation where controllers need to request both services in order to be able to dispatch queries and commands. Besides, queries can also be subject to restrictions. And there was no real foundation for handling permissions. Here's a proposal to improve the situation, with the following goals:

- [x] A foundation for a system of voters, that would be used to check permissions.
- [x] The ability to attach permissions to a message.
- [x] A decorator for `Dispatcher` that checks the permissions attached to a command before
  forwarding it to the inner dispatcher.
- [x] Deprecate `CommandDispatcher` and `QueryDispatcher` in favor of `Dispatcher`.
- [x] Deprecate `AssertingDispatcher` in favor of `RestrictedDispatcher`.

## Introducing Permissions and Voters

The most convenient way to specify permissions would be using tags next to the `message_bus.handler` tag that specifies the command attached to the handler. It doesn't really matter whether it's a command or a query, what matters is that it requires permissions to be dispatched.

Consider the following message handler definition:

```yaml
services:  
  Acme\MenuService\Application\MessageBus\CreateMenuHandler:
    tags:
    - name: message_bus.handler
      command: Acme\MenuService\Application\MessageBus\CreateMenu
    - name: message_bus.permission
      permission: is_admin
    - name: message_bus.permission
      permission: can_write_menu
```

Voters would be defined as tagged services. They would be identified with the tag `message_bus.voter` and the `key` attribute would match the `permission` attribute of the `message_bus.permission` tag.

```yaml
services:
  Acme\MenuService\Presentation\Security\Voters\IsAdminVoter:
    tags:
    - { name: message_bus.voter, key: is_admin }

  Acme\MenuService\Presentation\Security\Voters\CanWriteMenu:
    tags:
    - { name: message_bus.voter, key: can_write_menu }
```

### Voters

In order for voters to make their decision, they would require a context with relevant information, for example, the JWT token attached to an HTTP request. It's difficult to imagine what could be relevant. The context needs to be flexible enough and a bag of objects can provide such flexibility.

```php
<?php

namespace ICanBoogie\MessageBus;

use LogicException;

final class Context
{
    /**
     * Adds an object to the context.
     */
    public function add(object $object): self
    {
        // …
    }

    /**
     * Returns the object matching the specified class.
     * 
     * @template T of object
     *
     * @param class-string<T> $class
     *
     * @return T
     *
     * @throws NotInContext if the context doesn't have an object matching the specified class.
     */
    public function get(string $class): object
    {
         // …
    }
}
```

A voter could be as simple as saying "Yes, I'm granting permission. Look no further".

```php
<?php

namespace ICanBoogie\MessageBus;

interface Voter
{
    /**
     * Returns `true` when permission is granted, ending the voting process positively.
     */
    public function isGranted(object $message, Context $context): bool;
}
```

Now that we have voters, we need a voter provider.

```php
<?php

namespace ICanBoogie\MessageBus;

interface VoterProvider
{
    /**
     * Returns a voter for a permission.
     *
     * The dispatcher should fail if the function returns `null`, but a chain of voter providers
     * could invoke the next voter provider.
     *
     * @throws VoterNotFound if there's no voter for the permission.
     */
    public function getVoterForPermission(string $permission): ?Voter;
}
```

### Permissions

We could reuse the `Dispatcher` interface if the context was made optional, but with improper decoration, the context could be stripped and permissions skipped. It's safer to create a new interface that requires a context parameter.

```php
<?php

namespace ICanBoogie\MessageBus;

/**
 * A message dispatcher with some restrictions.
 */
interface RestrictedDispatcher
{
    /**
     * @throws PermissionNotGranted
     */
    public function dispatch(object $message, Context $context): mixed;
}
```

Regarding permissions, we need a map of permissions per message. That map could easily be created by a compiler pass, looking for the tag `message_bus.handler` to find the command, and the `message_bus.permission` tag to find the permissions. That map could then be used by a decorator to check for permissions.
